// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX7hkyiXtq0lqPlQv5gjaHyH8CshlQT6w',
    appId: '1:429535565319:android:eee1b45d060124d085bca2',
    messagingSenderId: '429535565319',
    projectId: 'fluttertask-e528a',
    storageBucket: 'fluttertask-e528a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE75pQu3XJLzwI9N06wXhUnR40uQPhVkY',
    appId: '1:429535565319:ios:ec397e852937700885bca2',
    messagingSenderId: '429535565319',
    projectId: 'fluttertask-e528a',
    storageBucket: 'fluttertask-e528a.firebasestorage.app',
    iosBundleId: 'com.example.bayantzFlutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7K24W_5nJaieh5YINX0NPSp5b5UtyjbA',
    appId: '1:429535565319:web:fbb3e16289fdfbcb85bca2',
    messagingSenderId: '429535565319',
    projectId: 'fluttertask-e528a',
    authDomain: 'fluttertask-e528a.firebaseapp.com',
    storageBucket: 'fluttertask-e528a.firebasestorage.app',
    measurementId: 'G-09036R0R49',
  );
}
